apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nextapp
  template:
    metadata: 
      name: nextapp
      labels:
        app: nextapp
    spec:
      containers:
      - name: nextapp
        image: ramachandrampm/myapp:latest
